use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

workspace 'ApodKMP'

target 'ApodKMP' do
    platform :ios, '11.0'
    project 'ApodKMP.xcodeproj'
    pod 'PINRemoteImage'
    pod 'SnapKit', '~> 5.0.0'
end

target 'apodmac' do
    platform :osx, '10.6'
    project 'apodmac/apodmac.xcodeproj'
    #pod 'PINRemoteImage'
    #pod 'SnapKit', '~> 5.0.0'
end


